### ISSUE TITLE
关于mobel文件

### ISSUE THREAD

**Issue by 756719339** [lemonhu/open-entity-relation-extraction#3]
你好，我最近也在初学知识库构建，能不能麻烦您分享一下model文件，感谢。

**Comment by lemonhu** [comment]
这个主要是基于依存句法分析做的7种DSNF范式，实现知识三元组抽取，没有model文件的。

**Comment by lemonhu** [comment]
我可能理解错了，你提到的模型文件应该是LTP模型文件，LTP官方网页上可以下载，链接为http://ltp.ai/download.html
