### ISSUE TITLE
您好，运行代码demo的时候报错postpostagger index越界，请问如何调整呢 

### ISSUE THREAD

**Issue by haoyuanzhe** [lemonhu/open-entity-relation-extraction#4]
Postagger: Model not loaded!
Traceback (most recent call last):
  File "extract_demo.py", line 36, in <module>
    words_postag = nlp.postag(lemmas)
  File "../core/nlp.py", line 89, in postag
    word = WordUnit(i+1, lemmas[i], postags[i])
IndexError: Index out of range

**Comment by lemonhu** [comment]
LTP的模型文件没有加载，应该是模型文件没有放到根目录的model文件夹。

**Comment by haoyuanzhe** [comment]
问题学习了，多谢指导：）

**Comment by haoyuanzhe** [comment]
问题已经解决，感谢指导

**Comment by haoyuanzhe** [comment]
：）
