### ISSUE TITLE
求Main_Implementation_Content的中文说明

### ISSUE THREAD

**Issue by unstory** [lemonhu/open-entity-relation-extraction#7]
你好，请问有Main Implementation Content的说明文档，或者相关资料推荐吗？英文的看不懂意思

**Comment by lemonhu** [comment]
`Main Implementation Content`来自如下论文，论文内容也非常容易理解，建议深入阅读学习一下，英文困难的话，可以借助谷歌翻译哈。
Jia S, Li M, Xiang Y. Chinese Open Relation Extraction and Knowledge Base Establishment[J]. ACM Transactions on Asian and Low-Resource Language Information Processing (TALLIP), 2018, 17(3): 15.
